project_id = "zfjfkzvvjkmjyhcmkrxf"

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.manage-billing]
verify_jwt = false

[functions.send-wedding-invitation]
verify_jwt = false

[functions.admin-manage-user]
verify_jwt = false

[functions.validate-reset-token]
verify_jwt = false
